sensor:
  - platform: statistics
    name: home_import_power_peak_31d
    entity_id: sensor.eth_dongle_pro_power_delivered
    state_characteristic: value_max
    max_age:
      days: 31

template:
  - sensor:
      - name: "Fluvius Capacity Limit"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        unique_id: fluvius_capacity_limit
        availability: >
          {{ states('input_number.ev_main_limit_w') not in ['unknown', 'unavailable', None] and
             states('sensor.home_import_power_peak_31d') not in ['unknown', 'unavailable', None] }}
        state: >
          {% set contract_limit = states('input_number.ev_main_limit_w') | float(4000) %}
          {% set monthly_peak = states('sensor.home_import_power_peak_31d') | float(0) %}
          {% if monthly_peak > contract_limit %}
            {{ monthly_peak | round(0) }}
          {% else %}
            {{ contract_limit | round(0) }}
          {% endif %}
        attributes:
          friendly_name: "Fluvius Capaciteitslimiet (W)"

      - name: "Available Capacity"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        unique_id: available_capacity
        availability: >
          {{ states('sensor.fluvius_capacity_limit') not in ['unknown', 'unavailable', None] and
             states('sensor.eth_dongle_pro_power_delivered') not in ['unknown', 'unavailable', None] and
             states('sensor.eth_dongle_pro_power_returned') not in ['unknown', 'unavailable', None] }}
        state: >
          {% set limit = states('sensor.fluvius_capacity_limit') | float(0) %}
          {% set delivered = states('sensor.eth_dongle_pro_power_delivered') | float(0) %}
          {% set returned = states('sensor.eth_dongle_pro_power_returned') | float(0) %}
          {% set load = [delivered - returned, 0] | max %}
          {{ [limit - load, 0] | max | round(0) }}
        attributes:
          friendly_name: "Beschikbare capaciteit (W)"
