# Improved EV Load Balancer - Reduces unnecessary adjustments to prevent Kia app notifications
# Only adjusts when change is significant (>= 2A) or when safety requires it

input_number:
  ev_min_adjustment_amp:
    name: Minimale aanpassing amperage
    min: 1
    max: 3
    step: 0.5
    initial: 2
    unit_of_measurement: A
    icon: mdi:current-ac
    
  ev_adjustment_cooldown_seconds:
    name: Wachttijd tussen aanpassingen
    min: 30
    max: 300
    step: 30
    initial: 60
    unit_of_measurement: s
    icon: mdi:timer

input_datetime:
  ev_last_adjustment_time:
    name: Laatste aanpassing tijd
    has_date: true
    has_time: true
    icon: mdi:clock

template:
  - sensor:
      - name: "EV tijd sinds laatste aanpassing"
        unique_id: ev_time_since_last_adjustment
        state: >
          {% set last = states('input_datetime.ev_last_adjustment_time') %}
          {% if last not in ['unknown', 'unavailable', None] %}
            {% set last_ts = as_timestamp(last) %}
            {% set now_ts = as_timestamp(now()) %}
            {{ (now_ts - last_ts) | round(0) }}
          {% else %}
            999
          {% endif %}
        unit_of_measurement: s
        availability: >
          {{ states('input_datetime.ev_last_adjustment_time') not in ['unknown', 'unavailable', None] }}
          
      - name: "EV aanpassing toegestaan"
        unique_id: ev_adjustment_allowed
        state: >
          {% set cooldown = states('input_number.ev_adjustment_cooldown_seconds') | float(60) %}
          {% set elapsed = states('sensor.ev_tijd_sinds_laatste_aanpassing') | float(999) %}
          {{ elapsed >= cooldown }}

automation:
  - alias: "EV Load Balancer: Verbeterde aanpassing met minder notificaties"
    id: ev_load_balancer_improved_adjust
    mode: single
    max_exceeded: silent
    trigger:
      - platform: time_pattern
        seconds: "/30"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sensor.ev_available_capacity
        for:
          seconds: 10
    condition:
      - condition: state
        entity_id: input_boolean.ev_force_max
        state: "off"
      - condition: state
        entity_id: binary_sensor.ev_load_balancer_ready
        state: "on"
    action:
      - variables:
          voltage_avg: >
            {% set readings = namespace(values=[]) %}
            {% for candidate in [
              'sensor.eth_dongle_pro_voltage_l1',
              'sensor.eth_dongle_pro_voltage_l2',
              'sensor.eth_dongle_pro_voltage_l3'
            ] %}
              {% set raw = states(candidate) %}
              {% if raw not in ['unknown', 'unavailable', None] %}
                {% set readings.values = readings.values + [raw | float(0)] %}
              {% endif %}
            {% endfor %}
            {% if readings.values %}
              {{ (readings.values | sum / readings.values | length) | round(1) }}
            {% else %}
              230
            {% endif %}
          available_power: "{{ states('sensor.ev_available_capacity') | float(0) }}"
          current_amp: >
            {% set sensor_val = state_attr('sensor.wallbox_kristof_riebbels_max_laadstroom', 'value') %}
            {% if sensor_val not in [None, 'unknown', 'unavailable'] %}
              {{ sensor_val | float(0) }}
            {% else %}
              {{ states('input_number.ev_last_set_current_a') | float(0) }}
            {% endif %}
          min_amp: "{{ states('input_number.wallbox_min_amp') | float(6) }}"
          max_amp: "{{ states('input_number.wallbox_max_amp') | float(16) }}"
          min_adjustment: "{{ states('input_number.ev_min_adjustment_amp') | float(2) }}"
          hysteresis_w: "{{ states('input_number.ev_hysteresis_w') | float(0) }}"
          
      - variables:
          target_amp: >
            {% set calculated = (available_power / voltage_avg) | round(0) %}
            {{ [min_amp, [calculated, max_amp] | min] | max }}
          amp_difference: "{{ (target_amp - current_amp) | abs }}"
          needs_immediate_action: >
            {{ available_power < 0 or target_amp < min_amp }}
          
      - choose:
          # Immediate safety action - always execute
          - conditions:
              - condition: template
                value_template: "{{ needs_immediate_action }}"
            sequence:
              - choose:
                  # Need to pause charging
                  - conditions:
                      - condition: template
                        value_template: "{{ target_amp < min_amp }}"
                    sequence:
                      - service: switch.turn_on
                        target:
                          entity_id: switch.wallbox_kristof_riebbels_pauzeren_hervatten
                      - service: input_datetime.set_datetime
                        target:
                          entity_id: input_datetime.ev_last_adjustment_time
                        data:
                          datetime: "{{ now() }}"
                      - service: persistent_notification.create
                        data:
                          title: "EV Laden gepauzeerd"
                          message: "Laden gepauzeerd vanwege capaciteitslimiet"
                          notification_id: ev_charging_paused
                          
          # Normal adjustments - only if significant change and cooldown passed
          - conditions:
              - condition: template
                value_template: "{{ amp_difference >= min_adjustment }}"
              - condition: state
                entity_id: sensor.ev_aanpassing_toegestaan
                state: "true"
            sequence:
              - service: number.set_value
                target:
                  entity_id: number.wallbox_kristof_riebbels_maximale_laadstroom
                data:
                  value: "{{ target_amp }}"
              - service: input_number.set_value
                target:
                  entity_id: input_number.ev_last_set_current_a
                data:
                  value: "{{ target_amp }}"
              - service: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.ev_last_adjustment_time
                data:
                  datetime: "{{ now() }}"
              # Resume if it was paused
              - condition: template
                value_template: >
                  {{ is_state('switch.wallbox_kristof_riebbels_pauzeren_hervatten', 'on') }}
              - service: switch.turn_off
                target:
                  entity_id: switch.wallbox_kristof_riebbels_pauzeren_hervatten
              - service: persistent_notification.dismiss
                data:
                  notification_id: ev_charging_paused
                  
  # Clear last adjustment time when force max is enabled
  - alias: "EV Load Balancer: Reset bij force max"
    id: ev_load_balancer_reset_on_force_max
    trigger:
      - platform: state
        entity_id: input_boolean.ev_force_max
        to: "on"
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.ev_last_adjustment_time
        data:
          datetime: "{{ now() - timedelta(minutes=10) }}"