# Smart Appliance Monitoring and Notifications
# Only notify when appliances are interrupted or when manual intervention is needed

input_boolean:
  dishwasher_notify_on_interruption:
    name: Vaatwasser onderbreking meldingen
    initial: true
    
  washing_machine_notify_on_interruption:
    name: Wasmachine onderbreking meldingen
    initial: true
    
  dryer_notify_on_interruption:
    name: Droogkast onderbreking meldingen
    initial: true

template:
  - sensor:
      - name: "Vaatwasser status"
        unique_id: dishwasher_status
        state: >
          {% set power = states('sensor.vaatwas_power') | float(0) %}
          {% set switch = states('switch.vaatwas') %}
          {% if switch == 'off' %}
            uitgeschakeld
          {% elif power > 100 %}
            actief
          {% elif power > 5 %}
            standby
          {% else %}
            inactief
          {% endif %}
        attributes:
          power: "{{ states('sensor.vaatwas_power') | float(0) }}"
          switch_state: "{{ states('switch.vaatwas') }}"
          
      - name: "Wasmachine status"
        unique_id: washing_machine_status
        state: >
          {% set power = states('sensor.metered_wall_plug_switch_power') | float(0) %}
          {% set switch = states('switch.metered_wall_plug_switch') %}
          {% if switch == 'off' %}
            uitgeschakeld
          {% elif power > 100 %}
            actief
          {% elif power > 5 %}
            standby
          {% else %}
            inactief
          {% endif %}
        attributes:
          power: "{{ states('sensor.metered_wall_plug_switch_power') | float(0) }}"
          switch_state: "{{ states('switch.metered_wall_plug_switch') }}"
          
      - name: "Droogkast status"
        unique_id: dryer_status
        state: >
          {% set power = states('sensor.droogkast_power') | float(0) %}
          {% set switch = states('switch.droogkast') %}
          {% if switch == 'off' %}
            uitgeschakeld
          {% elif power > 100 %}
            actief
          {% elif power > 5 %}
            standby
          {% else %}
            inactief
          {% endif %}
        attributes:
          power: "{{ states('sensor.droogkast_power') | float(0) }}"
          switch_state: "{{ states('switch.droogkast') }}"

automation:
  # Only notify when appliance was running and gets turned off (interrupted)
  - alias: "Smart Appliances: Vaatwasser onderbroken melding"
    id: smart_appliances_dishwasher_interrupted
    trigger:
      - platform: state
        entity_id: switch.vaatwas
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.dishwasher_notify_on_interruption
        state: 'on'
      - condition: template
        value_template: >
          {{ trigger.from_state.attributes.power | float(0) > 100 }}
    action:
      - service: persistent_notification.create
        data:
          title: "Vaatwasser onderbroken"
          message: >
            De vaatwasser is uitgeschakeld terwijl deze actief was. 
            Dit kan door capaciteitsbeheer zijn gebeurd.
          notification_id: dishwasher_interrupted

  - alias: "Smart Appliances: Wasmachine onderbroken melding"
    id: smart_appliances_washing_machine_interrupted
    trigger:
      - platform: state
        entity_id: switch.metered_wall_plug_switch
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.washing_machine_notify_on_interruption
        state: 'on'
      - condition: template
        value_template: >
          {{ trigger.from_state.attributes.power | float(0) > 100 }}
    action:
      - service: persistent_notification.create
        data:
          title: "Wasmachine onderbroken"
          message: >
            De wasmachine is uitgeschakeld terwijl deze actief was. 
            Dit kan door capaciteitsbeheer zijn gebeurd.
          notification_id: washing_machine_interrupted

  - alias: "Smart Appliances: Droogkast onderbroken melding"
    id: smart_appliances_dryer_interrupted  
    trigger:
      - platform: state
        entity_id: switch.droogkast
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.dryer_notify_on_interruption
        state: 'on'
      - condition: template
        value_template: >
          {{ trigger.from_state.attributes.power | float(0) > 100 }}
    action:
      - service: persistent_notification.create
        data:
          title: "Droogkast onderbroken"
          message: >
            De droogkast is uitgeschakeld terwijl deze actief was. 
            Dit kan door capaciteitsbeheer zijn gebeurd.
          notification_id: dryer_interrupted
          
  # Clear notifications when appliance is turned back on
  - alias: "Smart Appliances: Clear vaatwasser melding"
    id: smart_appliances_clear_dishwasher_notification
    trigger:
      - platform: state
        entity_id: switch.vaatwas
        to: 'on'
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: dishwasher_interrupted
          
  - alias: "Smart Appliances: Clear wasmachine melding"
    id: smart_appliances_clear_washing_machine_notification
    trigger:
      - platform: state
        entity_id: switch.metered_wall_plug_switch
        to: 'on'
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: washing_machine_interrupted
          
  - alias: "Smart Appliances: Clear droogkast melding"
    id: smart_appliances_clear_dryer_notification
    trigger:
      - platform: state
        entity_id: switch.droogkast
        to: 'on'
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: dryer_interrupted