# Capaciteitstarief Monitoring - Aanvullende sensors voor België
# Dit package voegt extra monitoring toe voor het capaciteitstarief

template:
  - sensor:
      # Kwartier monitoring (capaciteitstarief wordt per kwartier berekend)
      - name: "Kwartier gemiddeld vermogen"
        unique_id: quarter_average_power
        state: >
          {% set power = states('sensor.eth_dongle_pro_power_delivered') | float(0) %}
          {{ power | round(0) }}
        unit_of_measurement: W
        device_class: power
        attributes:
          info: "Huidige vermogen - digitale meter berekent werkelijk kwartiergemiddelde"
          
      # Voorspelling van nieuwe maandpiek
      - name: "Voorspelde maandpiek indien nu stoppen"
        unique_id: predicted_month_peak_if_stop_now
        state: >
          {% set current_peak = states('sensor.home_import_power_peak_31d') | float(0) %}
          {% set current_power = states('sensor.ev_house_power') | float(0) %}
          {{ [current_peak, current_power] | max | round(0) }}
        unit_of_measurement: W
        device_class: power
        attributes:
          current_month_peak: "{{ states('sensor.home_import_power_peak_31d') | round(0) }} W"
          current_usage: "{{ states('sensor.ev_house_power') | round(0) }} W"
          will_set_new_peak: "{{ states('sensor.ev_house_power') | float(0) > states('sensor.home_import_power_peak_31d') | float(0) }}"
          
      # Capaciteit ruimte tot volgende drempel
      - name: "Ruimte tot volgende kW drempel"
        unique_id: capacity_headroom_to_next_kw
        state: >
          {% set current_peak = states('sensor.home_import_power_peak_31d') | float(0) / 1000 %}
          {% set next_kw = (current_peak | int) + 1 %}
          {% set headroom = (next_kw - current_peak) * 1000 %}
          {{ headroom | round(0) }}
        unit_of_measurement: W
        attributes:
          current_peak_kw: "{{ (states('sensor.home_import_power_peak_31d') | float(0) / 1000) | round(2) }} kW"
          next_threshold_kw: "{{ ((states('sensor.home_import_power_peak_31d') | float(0) / 1000) | int) + 1 }} kW"
          
      # Geschatte maandelijkse kost capaciteitstarief
      - name: "Geschatte capaciteitstarief kost"
        unique_id: estimated_capacity_tariff_cost
        state: >
          {# Energie.be capaciteitstarief is ongeveer 2.5-3.5 EUR/kW/maand #}
          {% set tariff_per_kw = 3.0 %}
          {% set peak_kw = states('sensor.home_import_power_peak_31d') | float(0) / 1000 %}
          {% set minimum_kw = 2.5 %}
          {% set billable_kw = [peak_kw, minimum_kw] | max %}
          {{ (billable_kw * tariff_per_kw) | round(2) }}
        unit_of_measurement: "€"
        device_class: monetary
        attributes:
          peak_kw: "{{ (states('sensor.home_import_power_peak_31d') | float(0) / 1000) | round(2) }}"
          tariff_per_kw: "3.0 €/kW (schatting)"
          note: "Werkelijke tarief zie je energiefactuur"

  - binary_sensor:
      # Waarschuwingen voor capaciteitsdrempels
      - name: "Capaciteit boven 5 kW"
        unique_id: capacity_above_5kw
        state: >
          {{ states('sensor.ev_house_power') | float(0) > 5000 }}
        attributes:
          current_power: "{{ states('sensor.ev_house_power') | round(0) }} W"
          
      - name: "Capaciteit boven 6 kW"
        unique_id: capacity_above_6kw
        state: >
          {{ states('sensor.ev_house_power') | float(0) > 6000 }}
        attributes:
          current_power: "{{ states('sensor.ev_house_power') | round(0) }} W"
          
      - name: "Capaciteit boven 7 kW"
        unique_id: capacity_above_7kw
        state: >
          {{ states('sensor.ev_house_power') | float(0) > 7000 }}
        attributes:
          current_power: "{{ states('sensor.ev_house_power') | round(0) }} W"
          
      # Kwartier bijna voorbij waarschuwing
      - name: "Hoog verbruik laatste 5 min kwartier"
        unique_id: high_usage_quarter_ending
        state: >
          {% set minute = now().minute %}
          {% set mins_in_quarter = minute % 15 %}
          {% set mins_remaining = 15 - mins_in_quarter %}
          {% set high_power = states('sensor.ev_house_power') | float(0) > states('sensor.home_import_power_peak_31d') | float(0) %}
          {{ mins_remaining <= 5 and high_power }}
        attributes:
          minutes_remaining: >
            {% set minute = now().minute %}
            {% set mins_in_quarter = minute % 15 %}
            {{ 15 - mins_in_quarter }}

# Automations voor slimme waarschuwingen
automation:
  - alias: "Capaciteit: Waarschuw bij naderen kW drempel"
    id: capacity_warn_approaching_threshold
    trigger:
      - platform: numeric_state
        entity_id: sensor.ruimte_tot_volgende_kw_drempel
        below: 500
        for:
          seconds: 30
    condition:
      - condition: numeric_state
        entity_id: sensor.ev_house_power
        above: 3000
    action:
      - service: persistent_notification.create
        data:
          title: "⚡ Nadert volgende kW drempel"
          message: >
            Je bent {{ states('sensor.ruimte_tot_volgende_kw_drempel') }}W verwijderd van de volgende kW drempel.
            Huidige piek: {{ (states('sensor.home_import_power_peak_31d') | float(0) / 1000) | round(2) }} kW
            Dit kan je maandelijkse kost verhogen met ~3€
          notification_id: approaching_kw_threshold
          
  - alias: "Capaciteit: Clear drempel waarschuwing"
    id: capacity_clear_threshold_warning
    trigger:
      - platform: numeric_state
        entity_id: sensor.ruimte_tot_volgende_kw_drempel
        above: 1000
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: approaching_kw_threshold