# Gas Monitoring - Energie.be België
# Gebaseerd op tariefkaart GRN (Groene energie)

input_number:
  # Energie.be gas tarieven (uit tariefkaart)
  gas_energiekost_per_kwh:
    name: Gas energiekost per kWh
    min: 0
    max: 0.2
    step: 0.0001
    initial: 0.0329  # 3,29 cent/kWh uit tariefkaart
    unit_of_measurement: "€/kWh"
    icon: mdi:currency-eur
    mode: box
    
  gas_vaste_vergoeding_jaar:
    name: Gas vaste vergoeding per jaar
    min: 0
    max: 100
    step: 0.01
    initial: 65.00  # €65/jaar uit tariefkaart
    unit_of_measurement: "€/jaar"
    icon: mdi:currency-eur
    mode: box
    
  gas_btw_percentage:
    name: BTW percentage gas
    min: 0
    max: 25
    step: 1
    initial: 21
    unit_of_measurement: "%"
    icon: mdi:percent
    
  # Conversie factor m³ naar kWh (standaard voor aardgas in België)
  gas_conversie_factor:
    name: Gas conversie factor m³ naar kWh
    min: 10
    max: 12
    step: 0.01
    initial: 11.25  # Gemiddelde waarde voor België
    unit_of_measurement: "kWh/m³"
    icon: mdi:swap-horizontal

template:
  - sensor:
      # Gas verbruik in kWh
      - name: "Gas verbruik kWh"
        unique_id: gas_consumption_kwh
        state: >
          {% set m3 = states('sensor.eth_dongle_pro_gas_delivered') | float(0) %}
          {% set factor = states('input_number.gas_conversie_factor') | float(11.25) %}
          {{ (m3 * factor) | round(2) }}
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        availability: >
          {{ states('sensor.eth_dongle_pro_gas_delivered') not in ['unknown', 'unavailable', None] }}
          
      # Dagelijks gas verbruik
      - name: "Gas verbruik vandaag"
        unique_id: gas_consumption_today
        state: >
          {% set gas_today_m3 = states('sensor.eth_dongle_pro_gas_delivered_daily') | float(0) %}
          {% set factor = states('input_number.gas_conversie_factor') | float(11.25) %}
          {{ (gas_today_m3 * factor) | round(2) }}
        unit_of_measurement: "kWh"
        device_class: energy
        attributes:
          m3_today: "{{ states('sensor.eth_dongle_pro_gas_delivered_daily') | float(0) | round(3) }}"
          
      # Gas kosten vandaag
      - name: "Gas kosten vandaag"
        unique_id: gas_cost_today
        state: >
          {% set kwh_today = states('sensor.gas_verbruik_vandaag') | float(0) %}
          {% set price_per_kwh = states('input_number.gas_energiekost_per_kwh') | float(0.0329) %}
          {% set daily_fixed = states('input_number.gas_vaste_vergoeding_jaar') | float(65) / 365 %}
          {% set subtotal = (kwh_today * price_per_kwh) + daily_fixed %}
          {% set btw = states('input_number.gas_btw_percentage') | float(21) / 100 %}
          {{ (subtotal * (1 + btw)) | round(2) }}
        unit_of_measurement: "€"
        device_class: monetary
        attributes:
          energy_cost: "{{ (states('sensor.gas_verbruik_vandaag') | float(0) * states('input_number.gas_energiekost_per_kwh') | float(0.0329)) | round(2) }}"
          fixed_cost_daily: "{{ (states('input_number.gas_vaste_vergoeding_jaar') | float(65) / 365) | round(2) }}"
          btw_amount: >
            {% set kwh_today = states('sensor.gas_verbruik_vandaag') | float(0) %}
            {% set price_per_kwh = states('input_number.gas_energiekost_per_kwh') | float(0.0329) %}
            {% set daily_fixed = states('input_number.gas_vaste_vergoeding_jaar') | float(65) / 365 %}
            {% set subtotal = (kwh_today * price_per_kwh) + daily_fixed %}
            {% set btw = states('input_number.gas_btw_percentage') | float(21) / 100 %}
            {{ (subtotal * btw) | round(2) }}
            
      # Maandelijkse gas kosten schatting
      - name: "Gas kosten schatting deze maand"
        unique_id: gas_cost_month_estimate
        state: >
          {% set days_in_month = now().day %}
          {% set daily_cost = states('sensor.gas_kosten_vandaag') | float(0) %}
          {% set month_so_far = daily_cost * days_in_month %}
          {% set days_total = 30 %}
          {% set estimate = (month_so_far / days_in_month * days_total) if days_in_month > 0 else 0 %}
          {{ estimate | round(2) }}
        unit_of_measurement: "€"
        device_class: monetary
        attributes:
          based_on_days: "{{ now().day }}"
          average_per_day: "{{ (states('sensor.gas_kosten_vandaag') | float(0)) | round(2) }}"
          
      # Gas verbruik per uur (voor monitoring)
      - name: "Gas verbruik per uur"
        unique_id: gas_consumption_hourly_rate
        state: >
          {# Bereken verbruik over laatste uur #}
          {% set current_m3 = states('sensor.eth_dongle_pro_gas_delivered') | float(0) %}
          {% set factor = states('input_number.gas_conversie_factor') | float(11.25) %}
          {# Dit is een benadering - werkelijke hourly rate zou history nodig hebben #}
          {{ 0 }}
        unit_of_measurement: "kWh/h"
        attributes:
          note: "Implementeer met history statistics voor accurate waarde"

  - binary_sensor:
      # Hoog gasverbruik detectie
      - name: "Hoog gasverbruik actief"
        unique_id: high_gas_consumption_active
        state: >
          {% set hourly = states('sensor.gas_verbruik_per_uur') | float(0) %}
          {{ hourly > 3 }}  # Meer dan 3 kWh/h is hoog voor huishoudelijk gebruik
        attributes:
          current_rate: "{{ states('sensor.gas_verbruik_per_uur') }} kWh/h"
          threshold: "3 kWh/h"

# Utility meters voor gas tracking
utility_meter:
  gas_consumption_daily:
    source: sensor.gas_verbruik_kwh
    cycle: daily
    
  gas_consumption_weekly:
    source: sensor.gas_verbruik_kwh
    cycle: weekly
    
  gas_consumption_monthly:
    source: sensor.gas_verbruik_kwh
    cycle: monthly
    
  gas_consumption_yearly:
    source: sensor.gas_verbruik_kwh
    cycle: yearly

# Automations voor gas monitoring
automation:
  - alias: "Gas: Dagelijkse verbruik samenvatting"
    id: gas_daily_consumption_summary
    trigger:
      - platform: time
        at: "23:50:00"
    action:
      - service: persistent_notification.create
        data:
          title: "Gas Verbruik Vandaag"
          message: >
            Verbruik: {{ states('sensor.gas_verbruik_vandaag') | float(0) | round(1) }} kWh
            Kosten: €{{ states('sensor.gas_kosten_vandaag') | float(0) | round(2) }}
            Geschatte maandkosten: €{{ states('sensor.gas_kosten_schatting_deze_maand') | float(0) | round(2) }}
          notification_id: gas_daily_summary
          
# Scripts voor gas analyse
script:
  analyze_gas_usage:
    alias: "Analyseer Gas Verbruik"
    sequence:
      - service: system_log.write
        data:
          message: >
            === GAS VERBRUIK ANALYSE ===
            Vandaag: {{ states('sensor.gas_verbruik_vandaag') }} kWh (€{{ states('sensor.gas_kosten_vandaag') }})
            Deze maand: {{ states('sensor.gas_consumption_monthly') }} kWh
            Tarief: €{{ states('input_number.gas_energiekost_per_kwh') }}/kWh + €{{ states('input_number.gas_vaste_vergoeding_jaar') }}/jaar
            ===========================
          level: warning