# EV Laadsessie Tracking
# Volg laadsessies en bereken kosten

input_datetime:
  ev_laadsessie_start:
    name: EV Laadsessie Start
    has_date: true
    has_time: true
    icon: mdi:play
    
input_number:
  ev_laadsessie_kwh:
    name: EV Laadsessie kWh
    min: 0
    max: 100
    step: 0.01
    initial: 0
    unit_of_measurement: kWh
    icon: mdi:battery-charging
    mode: box

template:
  - sensor:
      # Huidige laadsessie duur
      - name: "EV Laadsessie Duur"
        unique_id: ev_charging_session_duration
        state: >
          {% if states('sensor.wallbox_kristof_riebbels_laadvermogen') | float(0) > 100 %}
            {% set start = states('input_datetime.ev_laadsessie_start') %}
            {% if start not in ['unknown', 'unavailable', None] %}
              {% set start_ts = as_timestamp(start) %}
              {% set now_ts = as_timestamp(now()) %}
              {% set duration = now_ts - start_ts %}
              {{ (duration / 3600) | round(2) }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "uur"
        icon: mdi:timer
        
      # Geschatte kWh deze sessie
      - name: "EV Laadsessie kWh Schatting"
        unique_id: ev_session_kwh_estimate
        state: >
          {% set power_w = states('sensor.wallbox_kristof_riebbels_laadvermogen') | float(0) %}
          {% set duration_h = states('sensor.ev_laadsessie_duur') | float(0) %}
          {% set kwh = (power_w / 1000 * duration_h) %}
          {{ kwh | round(2) }}
        unit_of_measurement: kWh
        device_class: energy
        
      # Kosten huidige laadsessie
      - name: "EV Laadsessie Kosten"
        unique_id: ev_session_cost
        state: >
          {% set kwh = states('sensor.ev_laadsessie_kwh_schatting') | float(0) %}
          {% set price = states('input_number.elektriciteit_energieprijs') | float(0.25) %}
          {{ (kwh * price) | round(2) }}
        unit_of_measurement: "€"
        device_class: monetary
        attributes:
          kwh: "{{ states('sensor.ev_laadsessie_kwh_schatting') }}"
          price_per_kwh: "{{ states('input_number.elektriciteit_energieprijs') }}"
          duration_hours: "{{ states('sensor.ev_laadsessie_duur') }}"
          
      # Laadsnelheid
      - name: "EV Laadsnelheid"
        unique_id: ev_charging_speed
        state: >
          {% set power_kw = states('sensor.wallbox_kristof_riebbels_laadvermogen') | float(0) / 1000 %}
          {% if power_kw > 0 %}
            {% set battery_size = 58.3 %}  # Kia EV3 battery size
            {% set current_soc = states('sensor.wallbox_kristof_riebbels_laadstatus') | float(50) %}
            {% set remaining_kwh = battery_size * (100 - current_soc) / 100 %}
            {% set hours_to_full = remaining_kwh / power_kw %}
            {{ hours_to_full | round(1) }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "uur tot vol"
        icon: mdi:speedometer
        attributes:
          current_power_kw: "{{ (states('sensor.wallbox_kristof_riebbels_laadvermogen') | float(0) / 1000) | round(1) }}"
          battery_soc: "{{ states('sensor.wallbox_kristof_riebbels_laadstatus') }}%"

# Automations voor sessie tracking
automation:
  - alias: "EV Sessie: Start detectie"
    id: ev_session_start_detection
    trigger:
      - platform: numeric_state
        entity_id: sensor.wallbox_kristof_riebbels_laadvermogen
        above: 100
        for:
          seconds: 30
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.ev_laadsessie_start
        data:
          datetime: "{{ now() }}"
      - service: input_number.set_value
        target:
          entity_id: input_number.ev_laadsessie_kwh
        data:
          value: 0
      - service: persistent_notification.create
        data:
          title: "🚗 EV Laadsessie Gestart"
          message: >
            Laden gestart om {{ now().strftime('%H:%M') }}
            Vermogen: {{ (states('sensor.wallbox_kristof_riebbels_laadvermogen') | float / 1000) | round(1) }} kW
          notification_id: ev_session_started
          
  - alias: "EV Sessie: Stop detectie"
    id: ev_session_stop_detection
    trigger:
      - platform: numeric_state
        entity_id: sensor.wallbox_kristof_riebbels_laadvermogen
        below: 50
        for:
          minutes: 2
    condition:
      - condition: numeric_state
        entity_id: sensor.ev_laadsessie_duur
        above: 0.1
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.ev_laadsessie_kwh
        data:
          value: "{{ states('sensor.ev_laadsessie_kwh_schatting') }}"
      - service: persistent_notification.create
        data:
          title: "✅ EV Laadsessie Voltooid"
          message: >
            Duur: {{ states('sensor.ev_laadsessie_duur') | float(0) | round(1) }} uur
            Energie: {{ states('sensor.ev_laadsessie_kwh_schatting') | float(0) | round(2) }} kWh
            Kosten: €{{ states('sensor.ev_laadsessie_kosten') | float(0) | round(2) }}
          notification_id: ev_session_completed

# Utility meter voor maandelijkse EV tracking
utility_meter:
  ev_charging_monthly:
    source: sensor.ev_laadsessie_kwh_schatting
    cycle: monthly
    
  ev_charging_yearly:
    source: sensor.ev_laadsessie_kwh_schatting
    cycle: yearly