# Recorder Optimization Package
# Alleen automations voor database maintenance
# De recorder configuratie zelf moet in configuration.yaml!

# Automation to manually purge old data periodically
automation:
  - alias: "Recorder: Extra purge oude data"
    id: recorder_extra_purge
    trigger:
      - platform: time
        at: "03:30:00"
    condition:
      # Only run on Sundays
      - condition: time
        weekday:
          - sun
    action:
      - service: recorder.purge
        data:
          keep_days: 7
          repack: true
          
  - alias: "Recorder: Purge specifieke high-frequency entities"
    id: recorder_purge_high_frequency
    trigger:
      - platform: time
        at: "04:00:00"
    condition:
      # Run daily
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      # Remove data older than 2 days for very high frequency sensors
      - service: recorder.purge_entities
        data:
          keep_days: 2
          entity_globs:
            - sensor.*_linkquality
            - sensor.*_last_seen
            - sensor.*voltage*  # Voltage changes constantly
            - sensor.*current*   # Current changes constantly
            
# Helper script to check database size
script:
  check_database_info:
    alias: "Check Database Info"
    sequence:
      - service: system_log.write
        data:
          message: "Database optimization package loaded. Run 'recorder.purge' service with repack:true to reduce size immediately."
          level: warning