# Recorder Optimization Package
# Reduces database size and improves performance for backup operations

# BELANGRIJK: De recorder configuratie hieronder moet in configuration.yaml geplaatst worden!
# Kopieer alles tussen de "--- START RECORDER CONFIG ---" en "--- END RECORDER CONFIG ---" markers
# naar je configuration.yaml file.

# --- START RECORDER CONFIG ---
# recorder:
  # Increase commit interval to reduce disk I/O
  commit_interval: 30
  
  # Keep only 7 days of history instead of default 10
  purge_keep_days: 7
  
  # Enable auto purge and repack
  auto_purge: true
  auto_repack: true
  
  # Exclude high-frequency updates and unnecessary data
  exclude:
    domains:
      # System domains that change frequently but aren't needed in history
      - automation
      - updater
      - camera
      - media_player
      - weather
      - sun
      - script
      - group
      - zone
      
    entity_globs:
      # Exclude frequently updating sensors that aren't critical
      - sensor.*_linkquality
      - sensor.*_last_seen
      - sensor.*_rssi
      - sensor.*_signal_strength
      - sensor.*uptime*
      - sensor.*time*
      - sensor.*date*
      - sensor.time_*
      - sensor.date_*
      - sensor.*_cpu_*
      - sensor.*_memory_*
      - sensor.*_disk_*
      - sensor.*_temperature  # System temps, not room temps
      - sensor.*_battery_temperature
      - binary_sensor.*_update_available
      - sensor.*_newest_version
      - sensor.*_last_restart
      - sensor.*_ip_address
      - sensor.*_mac_address
      - sensor.*_ssid
      
    entities:
      # Specific entities that update too frequently
      - sensor.time
      - sensor.date
      - sensor.time_date
      - sensor.internet_time
      - sensor.uptime
      - sensor.last_boot
      
    event_types:
      # Events that aren't needed in history
      - service_registered
      - service_removed
      - component_loaded
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - feedreader
      - service_executed
      - timer_out_of_sync
      - time_changed
      - state_write_error
      
  # Include only what we need for energy monitoring and automation
  include:
    domains:
      # Core domains for energy management
      - sensor
      - switch
      - number
      - input_number
      - input_boolean
      - input_select
      - binary_sensor
      - climate
      - device_tracker
      
    entity_globs:
      # Include all energy-related sensors
      - sensor.*power*
      - sensor.*energy*
      - sensor.*consumption*
      - sensor.*kwh*
      - sensor.*watt*
      - sensor.*capacity*
      - sensor.*peak*
      - sensor.eth_dongle_*
      - sensor.ev_*
      - sensor.wallbox_*
      - sensor.fluvius_*
      - sensor.*temperature  # Room temperatures
      - sensor.*humidity
      - sensor.*motion
      - sensor.*occupancy
      - switch.*vaatwas*
      - switch.*wasmachine*
      - switch.*droogkast*
      - switch.*waterker*
      - sensor.*vaatwas*
      - sensor.*wasmachine*  
      - sensor.*droogkast*
      - sensor.*waterker*

# Automation to manually purge old data periodically
automation:
  - alias: "Recorder: Extra purge oude data"
    id: recorder_extra_purge
    trigger:
      - platform: time
        at: "03:30:00"
    condition:
      # Only run on Sundays
      - condition: time
        weekday:
          - sun
    action:
      - service: recorder.purge
        data:
          keep_days: 7
          repack: true
          
  - alias: "Recorder: Purge specifieke high-frequency entities"
    id: recorder_purge_high_frequency
    trigger:
      - platform: time
        at: "04:00:00"
    condition:
      # Run daily
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      # Remove data older than 2 days for very high frequency sensors
      - service: recorder.purge_entities
        data:
          keep_days: 2
          entity_globs:
            - sensor.*_linkquality
            - sensor.*_last_seen
            - sensor.*voltage*  # Voltage changes constantly
            - sensor.*current*   # Current changes constantly
# --- END RECORDER CONFIG ---
            
# De automations hieronder kunnen wel in dit package blijven

# Helper script to check database size
script:
  check_database_info:
    alias: "Check Database Info"
    sequence:
      - service: system_log.write
        data:
          message: "Database optimization package loaded. Run 'recorder.purge' service with repack:true to reduce size immediately."
          level: warning