# /config/packages/appliance_evaluations.yaml
# Apparaat opstart evaluaties en slimme scheduling

# ========================================
# APPLIANCE START EVALUATIONS
# ========================================
automation:
  - id: wasmachine_opstart_evaluatie
    alias: "Wasmachine Opstart Evaluatie" 
    description: "Controleert of wasmachine veilig kan starten"
    trigger:
      - platform: state
        entity_id: switch.wasmachine_inschakelen
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.washing_machine_auto_mode
        state: 'on'
    action:
      - choose:
          # Genoeg capaciteit - direct starten
          - conditions:
              - condition: template
                value_template: >
                  {% set beschikbaar = states('sensor.beschikbaar_vermogen') | float(0) %}
                  {% set nodig = states('input_number.washing_machine_power_usage') | float(2200) %}
                  {{ beschikbaar > nodig }}
              - condition: template
                value_template: >
                  {{ not is_state('input_boolean.piek_blokkering', 'on') }}
            sequence:
              - service: notify.persistent_notification
                data:
                  title: "✅ Wasmachine start toegestaan"
                  message: >
                    Voldoende capaciteit beschikbaar.
                    Beschikbaar: {{ states('sensor.beschikbaar_vermogen') }}W
                    Nodig: {{ states('input_number.washing_machine_power_usage') }}W

          # Piek tarief - in wachtrij
          - conditions:
              - condition: state
                entity_id: input_boolean.piek_blokkering
                state: 'on'
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.wasmachine_inschakelen
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.wasmachine_wachtrij
              - service: notify.persistent_notification
                data:
                  title: "⏳ Wasmachine in wachtrij"
                  message: >
                    Piek tarief actief - start bij dal tarief.
                    Volgende dal: {{ states('sensor.electricity_tariff_next_change_time') }}
        default:
          # Onvoldoende capaciteit - in wachtrij
          - service: switch.turn_off
            target:
              entity_id: switch.wasmachine_inschakelen
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.wasmachine_wachtrij
          - service: notify.persistent_notification
            data:
              title: "⏳ Wasmachine uitgesteld"
              message: >
                Onvoldoende capaciteit.
                Beschikbaar: {{ states('sensor.beschikbaar_vermogen') }}W
                Nodig: {{ states('input_number.washing_machine_power_usage') }}W

  - id: droogkast_opstart_evaluatie
    alias: "Droogkast Opstart Evaluatie"
    description: "Controleert of droogkast veilig kan starten"
    trigger:
      - platform: state
        entity_id: switch.droogkast
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.dryer_auto_mode
        state: 'on'
    action:
      - choose:
          # Genoeg capaciteit - direct starten
          - conditions:
              - condition: template
                value_template: >
                  {% set beschikbaar = states('sensor.beschikbaar_vermogen') | float(0) %}
                  {% set nodig = states('input_number.dryer_power_usage') | float(2800) %}
                  {{ beschikbaar > nodig }}
              - condition: template
                value_template: >
                  {{ not is_state('input_boolean.piek_blokkering', 'on') }}
            sequence:
              - service: notify.persistent_notification
                data:
                  title: "✅ Droogkast start toegestaan"
                  message: >
                    Voldoende capaciteit beschikbaar.
                    Beschikbaar: {{ states('sensor.beschikbaar_vermogen') }}W
                    Nodig: {{ states('input_number.dryer_power_usage') }}W

          # Piek tarief - in wachtrij
          - conditions:
              - condition: state
                entity_id: input_boolean.piek_blokkering
                state: 'on'
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.droogkast
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.droogkast_wachtrij
              - service: notify.persistent_notification
                data:
                  title: "⏳ Droogkast in wachtrij"
                  message: >
                    Piek tarief actief - start bij dal tarief.
        default:
          # Onvoldoende capaciteit - in wachtrij
          - service: switch.turn_off
            target:
              entity_id: switch.droogkast
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.droogkast_wachtrij
          - service: notify.persistent_notification
            data:
              title: "⏳ Droogkast uitgesteld"
              message: >
                Onvoldoende capaciteit.
                Beschikbaar: {{ states('sensor.beschikbaar_vermogen') }}W
                Nodig: {{ states('input_number.dryer_power_usage') }}W

  - id: vaatwasser_opstart_evaluatie
    alias: "Vaatwasser Opstart Evaluatie"
    description: "Controleert of vaatwasser veilig kan starten"
    trigger:
      - platform: state
        entity_id: switch.vaatwas
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.dishwasher_auto_mode
        state: 'on'
    action:
      - choose:
          # Genoeg capaciteit - direct starten
          - conditions:
              - condition: template
                value_template: >
                  {% set beschikbaar = states('sensor.beschikbaar_vermogen') | float(0) %}
                  {% set nodig = states('input_number.dishwasher_power_usage') | float(2000) %}
                  {{ beschikbaar > nodig }}
              - condition: template
                value_template: >
                  {{ not is_state('input_boolean.piek_blokkering', 'on') }}
            sequence:
              - service: notify.persistent_notification
                data:
                  title: "✅ Vaatwasser start toegestaan"
                  message: >
                    Voldoende capaciteit beschikbaar.
                    Beschikbaar: {{ states('sensor.beschikbaar_vermogen') }}W
                    Nodig: {{ states('input_number.dishwasher_power_usage') }}W

          # Piek tarief - in wachtrij
          - conditions:
              - condition: state
                entity_id: input_boolean.piek_blokkering
                state: 'on'
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.vaatwas
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.vaatwasser_wachtrij
              - service: notify.persistent_notification
                data:
                  title: "⏳ Vaatwasser in wachtrij"
                  message: >
                    Piek tarief actief - start bij dal tarief.
        default:
          # Onvoldoende capaciteit - in wachtrij
          - service: switch.turn_off
            target:
              entity_id: switch.vaatwas
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.vaatwasser_wachtrij
          - service: notify.persistent_notification
            data:
              title: "⏳ Vaatwasser uitgesteld"
              message: >
                Onvoldoende capaciteit.
                Beschikbaar: {{ states('sensor.beschikbaar_vermogen') }}W
                Nodig: {{ states('input_number.dishwasher_power_usage') }}W