# /config/packages/evohome_climate_control.yaml
# Evohome climate control and heating management

# ========================================
# INPUT BOOLEANS - Climate Control
# ========================================
input_boolean:
  guest_mode:
    name: "Gast Modus"
    initial: false
    icon: mdi:account-multiple

  eco_mode:
    name: "Eco Modus"
    initial: false
    icon: mdi:leaf

  heating_override:
    name: "Verwarming Override"
    initial: false
    icon: mdi:thermostat

# ========================================
# INPUT NUMBERS - Temperature Settings
# ========================================
input_number:
  eco_temperature:
    name: "Eco Temperatuur"
    min: 5
    max: 20
    step: 0.5
    initial: 16
    unit_of_measurement: "°C"
    icon: mdi:thermometer

  night_temperature:
    name: "Nacht Temperatuur"
    min: 10
    max: 22
    step: 0.5
    initial: 18
    unit_of_measurement: "°C"
    icon: mdi:weather-night

  comfort_temperature:
    name: "Comfort Temperatuur"
    min: 18
    max: 25
    step: 0.5
    initial: 21
    unit_of_measurement: "°C"
    icon: mdi:home-thermometer

# ========================================
# SCRIPTS - Climate Control
# ========================================
script:
  evohome_away_mode:
    alias: "Evohome Away Mode"
    sequence:
      - service: climate.set_preset_mode
        target:
          entity_id: 
            - climate.douche
            - climate.evo
            - climate.keuken
            - climate.ramen
            - climate.torquoise
        data:
          preset_mode: "away"
      - service: notify.persistent_notification
        data:
          title: "🏠 Away Mode Actief"
          message: "Alle zones naar away temperatuur"

  evohome_home_mode:
    alias: "Evohome Home Mode"
    sequence:
      - service: climate.set_preset_mode
        target:
          entity_id: 
            - climate.douche
            - climate.evo
            - climate.keuken
            - climate.ramen
            - climate.torquoise
        data:
          preset_mode: "auto"
      - service: notify.persistent_notification
        data:
          title: "🏠 Home Mode Actief"
          message: "Alle zones naar normale temperatuur"

  evohome_night_mode:
    alias: "Evohome Night Mode"
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: 
            - climate.douche
            - climate.evo
            - climate.keuken
            - climate.ramen
            - climate.torquoise
        data:
          temperature: "{{ states('input_number.night_temperature') }}"
      - service: notify.persistent_notification
        data:
          title: "🌙 Nacht Modus Actief"
          message: "Temperatuur verlaagd naar {{ states('input_number.night_temperature') }}°C"

  evohome_morning_boost:
    alias: "Evohome Morning Boost"
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: 
            - climate.douche
            - climate.evo
            - climate.keuken
            - climate.ramen
            - climate.torquoise
        data:
          temperature: "{{ states('input_number.comfort_temperature') }}"
      - service: notify.persistent_notification
        data:
          title: "☀️ Ochtend Boost Actief"
          message: "Temperatuur verhoogd naar {{ states('input_number.comfort_temperature') }}°C"

  evohome_eco_mode:
    alias: "Evohome Eco Mode"
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: 
            - climate.douche
            - climate.evo
            - climate.keuken
            - climate.ramen
            - climate.torquoise
        data:
          temperature: "{{ states('input_number.eco_temperature') }}"
      - service: notify.persistent_notification
        data:
          title: "🍃 Eco Modus Actief"
          message: "Temperatuur verlaagd naar {{ states('input_number.eco_temperature') }}°C"

  evohome_guest_mode:
    alias: "Evohome Guest Mode"
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: 
            - climate.douche
            - climate.evo
            - climate.keuken
            - climate.ramen
            - climate.torquoise
        data:
          temperature: "{{ states('input_number.comfort_temperature') }}"
      - service: notify.persistent_notification
        data:
          title: "👥 Gast Modus Actief"
          message: "Comfort temperatuur voor gasten"

# ========================================
# AUTOMATIONS - Climate Schedule
# ========================================
automation:
  - id: evohome_away_automation
    alias: "Evohome: Set Away When Nobody Home"
    trigger:
      - platform: state
        entity_id: group.family
        to: 'not_home'
        for: "00:15:00"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
    action:
      - service: script.evohome_away_mode

  - id: evohome_home_automation
    alias: "Evohome: Set Home When Someone Returns"
    trigger:
      - platform: state
        entity_id: group.family
        to: 'home'
    action:
      - service: script.evohome_home_mode

  - id: evohome_night_mode
    alias: "Evohome: Night Mode"
    trigger:
      - platform: time
        at: "22:30:00"
    action:
      - service: script.evohome_night_mode

  - id: evohome_morning_boost
    alias: "Evohome: Morning Boost"
    trigger:
      - platform: time
        at: "06:30:00"
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    action:
      - service: script.evohome_morning_boost

  - id: evohome_peak_hours
    alias: "Evohome: Eco During Peak Hours"
    trigger:
      - platform: state
        entity_id: input_select.electricity_tariff_block
        to: "piek"
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    action:
      - service: script.evohome_eco_mode

  - id: evohome_startup_refresh
    alias: "Evohome: Refresh on HA Start"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "00:02:00"
      - service: evohome.refresh_system

  - id: evohome_guest_mode_toggle
    alias: "Evohome: Guest Mode Toggle"
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'on'
    action:
      - service: script.evohome_guest_mode

  - id: evohome_guest_mode_off
    alias: "Evohome: Guest Mode Off"
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'off'
    action:
      - service: script.evohome_home_mode

  - id: evohome_eco_mode_toggle
    alias: "Evohome: Eco Mode Toggle"
    trigger:
      - platform: state
        entity_id: input_boolean.eco_mode
        to: 'on'
    action:
      - service: script.evohome_eco_mode

  - id: evohome_eco_mode_off
    alias: "Evohome: Eco Mode Off"
    trigger:
      - platform: state
        entity_id: input_boolean.eco_mode
        to: 'off'
    action:
      - service: script.evohome_home_mode